fbone/appointment/models.py
# -*- coding: utf-8 -*-

from ..extensions import db
from ..utils import USERNAME_LEN_MAX
from .forms import MESSAGE_LEN_MAX, EMAIL_LEN_MAX, TIMEZONE_LEN_MAX


class Appointment(db.Model):

    __tablename__ = 'appointments'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(USERNAME_LEN_MAX), nullable=False)
    email = db.Column(db.String(EMAIL_LEN_MAX), nullable=False)
    start_time = db.Column(db.Integer, nullable=False)
    end_time = db.Column(db.Integer, nullable=False)
    timezone = db.Column(db.String(TIMEZONE_LEN_MAX), nullable=False)
    message = db.Column(db.String(MESSAGE_LEN_MAX), nullable=False)

fbone/settings/forms.py
# -*- coding: utf-8 -*-

from flask.ext.wtf import Form
from wtforms import (ValidationError, HiddenField, PasswordField, SubmitField)
from wtforms.validators import (Required, Length, EqualTo)
from flask.ext.login import current_user

from ..user import User
from ..utils import PASSWORD_LEN_MIN, PASSWORD_LEN_MAX


class PasswordForm(Form):
    next = HiddenField()
    password = PasswordField('Current password', [Required()])
    new_password = PasswordField('New password',
                                 [Required(),
                                  Length(PASSWORD_LEN_MIN, PASSWORD_LEN_MAX)])
    password_again = PasswordField('Password again',
                                   [Required(),
                                    Length(PASSWORD_LEN_MIN, PASSWORD_LEN_MAX),
                                    EqualTo('new_password')])
    submit = SubmitField(u'Save')

    def validate_password(form, field):
        user = User.get_by_id(current_user.id)
        if not user.check_password(field.data):
            raise ValidationError("Password is wrong.")

fbone/__init__.py
# -*- coding: utf-8 -*-

from app import create_app      # NOQA

fbone/api/__init__.py
# -*- coding: utf-8 -*-

from .views import api          # NOQA

fbone/api/views.py
# -*- coding: utf-8 -*-

from flask import Blueprint, current_app, request, jsonify
from flask.ext.login import login_user, current_user, logout_user

from ..user import User


api = Blueprint('api', __name__, url_prefix='/api')


@api.route('/login', methods=['POST'])
def login():
    if current_user.is_authenticated():
        return jsonify(flag='success')

    username = request.form.get('username')
    password = request.form.get('password')
    if username and password:
        user, authenticated = User.authenticate(username, password)
        if user and authenticated:
            if login_user(user, remember='y'):
                return jsonify(flag='success')

    current_app.logger.debug('login(api) failed, username: %s.' % username)
    return jsonify(flag='fail', msg='Sorry, try again.')


@api.route('/logout')
def logout():
    if current_user.is_authenticated():
        logout_user()
    return jsonify(flag='success', msg='Logouted.')

fbone/app.py
# -*- coding: utf-8 -*-

import os
from datetime import datetime

from flask import Flask, request, render_template
from flask.ext import login
from flask.ext.admin import Admin
from flask.ext.admin.contrib.sqla import ModelView
from flask.ext.babel import Babel
from flask.ext.debugtoolbar import DebugToolbarExtension

from .config import DefaultConfig
from .production_config import ProductionConfig
from .user import User, user
from .appointment import Appointment, appointment
from .settings import settings
from .frontend import frontend
from .api import api
from .extensions import db, mail, cache, login_manager, oid
# from .utils import INSTANCE_FOLDER_PATH


# For import *
__all__ = ['create_app']

DEFAULT_BLUEPRINTS = (
    appointment,
    frontend,
    user,
    settings,
    api,
)


def create_app(config=None, app_name=None, blueprints=None):
    """Create a Flask app."""

    if app_name is None:
        app_name = DefaultConfig.PROJECT
    if blueprints is None:
        blueprints = DEFAULT_BLUEPRINTS

    app = Flask(app_name)
    configure_app(app, config)
    configure_hook(app)
    configure_blueprints(app, blueprints)
    configure_extensions(app)
    configure_logging(app)
    configure_template_filters(app)
    configure_error_handlers(app)
    configure_admin(app)
    configure_debugtoolbar(app)

    return app


def configure_app(app, config=None):
    """Different ways of configurations."""

    # http://flask.pocoo.org/docs/api/#configuration
    if 'PRODUCTION' in os.environ:
        app.config.from_object(ProductionConfig)
    else:
        app.config.from_object(DefaultConfig)

    # http://flask.pocoo.org/docs/config/#instance-folders
    app.config.from_pyfile('production.cfg', silent=True)

    if config:
        app.config.from_object(config)

    # Use instance folder instead of env variables to make deployment easier.
    # app.config.from_envvar('%s_APP_CONFIG' % DefaultConfig.PROJECT.upper(),
    #                        silent=True)


def configure_extensions(app):
    # flask-sqlalchemy
    db.init_app(app)

    # flask-mail
    mail.init_app(app)

    # flask-cache
    cache.init_app(app)

    # flask-babel
    babel = Babel(app)

    @babel.localeselector
    def get_locale():
        accept_languages = app.config.get('ACCEPT_LANGUAGES')
        return request.accept_languages.best_match(accept_languages)

    # flask-login
    login_manager.login_view = 'frontend.login'
    login_manager.refresh_view = 'frontend.reauth'

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(id)
    login_manager.setup_app(app)

    # flask-openid
    oid.init_app(app)


def configure_blueprints(app, blueprints):
    """Configure blueprints in views."""

    for blueprint in blueprints:
        app.register_blueprint(blueprint)


def configure_template_filters(app):

    @app.template_filter()
    def pretty_date(value):
        return pretty_date(value)

    @app.template_filter()
    def format_date(value, format='%Y-%m-%d'):
        return value.strftime(format)


def configure_logging(app):
    """Configure file(info) and email(error) logging."""

    if app.debug or app.testing:
        # Skip debug and test mode. Just check standard output.
        return

    import logging
    from logging.handlers import SMTPHandler

    # Set info level on logger, which might be overwritten by handers.
    # Suppress DEBUG messages.
    app.logger.setLevel(logging.INFO)

    info_log = os.path.join(app.config['LOG_FOLDER'], 'info.log')
    info_file_handler = logging.handlers.RotatingFileHandler(info_log,
                                                             maxBytes=100000,
                                                             backupCount=10)
    info_file_handler.setLevel(logging.INFO)
    info_file_handler.setFormatter(logging.Formatter(
        '%(asctime)s %(levelname)s: %(message)s '
        '[in %(pathname)s:%(lineno)d]')
    )
    app.logger.addHandler(info_file_handler)

    # Testing
    #app.logger.info("testing info.")
    #app.logger.warn("testing warn.")
    #app.logger.error("testing error.")

    mail_handler = SMTPHandler(app.config['MAIL_SERVER'],
                               app.config['MAIL_USERNAME'],
                               app.config['ADMINS'],
                               'O_ops... %s failed!' % app.config['PROJECT'],
                               (app.config['MAIL_USERNAME'],
                                app.config['MAIL_PASSWORD']))
    mail_handler.setLevel(logging.ERROR)
    mail_handler.setFormatter(logging.Formatter(
        '%(asctime)s %(levelname)s: %(message)s '
        '[in %(pathname)s:%(lineno)d]')
    )
    app.logger.addHandler(mail_handler)


def configure_hook(app):
    @app.before_request
    def before_request():
        pass


def configure_error_handlers(app):

    @app.errorhandler(403)
    def forbidden_page(error):
        return render_template("errors/forbidden_page.html"), 403

    @app.errorhandler(404)
    def page_not_found(error):
        return render_template("errors/page_not_found.html"), 404

    @app.errorhandler(500)
    def server_error_page(error):
        return render_template("errors/server_error.html"), 500


def configure_admin(app):
    class UserView(ModelView):
        def is_accessible(self):
            return login.current_user.is_authenticated()

    class AppointmentView(ModelView):
        column_formatters = {
            "start_time": lambda v, c, m, p: datetime.utcfromtimestamp(m.start_time),  # NOQA
            "end_time": lambda v, c, m, p: datetime.utcfromtimestamp(m.end_time)  # NOQA
        }

        def is_accessible(self):
            return login.current_user.is_authenticated()

    admin = Admin(app)
    admin.add_view(UserView(User, db.session))
    admin.add_view(AppointmentView(Appointment, db.session))


def configure_debugtoolbar(app):
    DebugToolbarExtension(app)

fbone/appointment/__init__.py
# -*- coding: utf-8 -*-

from .models import Appointment  # NOQA
from .views import appointment   # NOQA

fbone/frontend/__init__.py
# -*- coding: utf-8 -*-

from .views import frontend     # NOQA

fbone/frontend/views.py
# -*- coding: utf-8 -*-

from uuid import uuid4

from flask import (Blueprint, render_template, current_app, request,
                   flash, url_for, redirect, session, abort)
from flask.ext.mail import Message
from flask.ext.babel import gettext as _
from flask.ext.login import (login_required, login_user, current_user,
                             logout_user, confirm_login, login_fresh)

from ..user import User
from ..extensions import db, mail, login_manager, oid
from .forms import (SignupForm, LoginForm, RecoverPasswordForm, ReauthForm,
                    ChangePasswordForm, OpenIDForm)


frontend = Blueprint('frontend', __name__)


@frontend.route('/login/openid', methods=['GET', 'POST'])
@oid.loginhandler
def login_openid():
    if current_user.is_authenticated():
        return redirect(url_for('user.index'))

    form = OpenIDForm()
    if form.validate_on_submit():
        openid = form.openid.data
        current_app.logger.debug('login with openid(%s)...' % openid)
        return oid.try_login(openid, ask_for=['email', 'fullname', 'nickname'])
    return render_template('frontend/login_openid.html',
                           form=form,
                           error=oid.fetch_error())


@oid.after_login
def create_or_login(resp):
    user = User.query.filter_by(openid=resp.identity_url).first()
    if user and login_user(user):
        flash('Logged in', 'success')
        return redirect(oid.get_next_url() or url_for('user.index'))
    return redirect(url_for('frontend.create_profile',
                            next=oid.get_next_url(),
                            name=resp.fullname or resp.nickname,
                            email=resp.email,
                            openid=resp.identity_url))


@frontend.route('/')
def index():
    current_app.logger.debug('debug')

    session.update(request.args.to_dict())
    return render_template('index.html')


@frontend.route('/search')
def search():
    keywords = request.args.get('keywords', '').strip()
    pagination = None
    if keywords:
        page = int(request.args.get('page', 1))
        pagination = User.search(keywords).paginate(page, 1)
    else:
        flash(_('Please input keyword(s)'), 'error')
    return render_template('frontend/search.html',
                           pagination=pagination,
                           keywords=keywords)


@frontend.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated():
        return redirect(url_for('user.index'))

    form = LoginForm(login=request.args.get('login', None),
                     next=request.args.get('next', None))

    if form.validate_on_submit():
        user, authenticated = User.authenticate(form.login.data,
                                                form.password.data)

        if user and authenticated:
            remember = request.form.get('remember') == 'y'
            if login_user(user, remember=remember):
                flash(_("Logged in"), 'success')
            return redirect(form.next.data or url_for('user.index'))
        else:
            flash(_('Sorry, invalid login'), 'error')

    return render_template('frontend/login.html', form=form)


@frontend.route('/reauth', methods=['GET', 'POST'])
@login_required
def reauth():
    form = ReauthForm(next=request.args.get('next'))

    if request.method == 'POST':
        user, authenticated = User.authenticate(current_user.name,
                                                form.password.data)
        if user and authenticated:
            confirm_login()
            current_app.logger.debug('reauth: %s' % session['_fresh'])
            flash(_('Reauthenticated.'), 'success')
            return redirect('/change_password')

        flash(_('Password is wrong.'), 'error')
    return render_template('frontend/reauth.html', form=form)


@frontend.route('/logout')
@login_required
def logout():
    logout_user()
    flash(_('Logged out'), 'success')
    return redirect(url_for('frontend.index'))


@frontend.route('/signup', methods=['GET', 'POST'])
def signup():
    if current_user.is_authenticated():
        return redirect(url_for('user.index'))

    form = SignupForm(next=request.args.get('next'))

    if form.validate_on_submit():
        user = User()
        form.populate_obj(user)

        db.session.add(user)
        db.session.commit()

        if login_user(user):
            return redirect(form.next.data or url_for('user.index'))

    return render_template('frontend/signup.html', form=form)


@frontend.route('/change_password', methods=['GET', 'POST'])
def change_password():
    user = None
    if current_user.is_authenticated():
        if not login_fresh():
            return login_manager.needs_refresh()
        user = current_user
    elif 'activation_key' in request.values and 'email' in request.values:
        activation_key = request.values['activation_key']
        email = request.values['email']
        user = User.query.filter_by(activation_key=activation_key) \
                         .filter_by(email=email).first()

    if user is None:
        abort(403)

    form = ChangePasswordForm(activation_key=user.activation_key)

    if form.validate_on_submit():
        user.password = form.password.data
        user.activation_key = None
        db.session.add(user)
        db.session.commit()

        flash(_("Your password has been changed, please log in again"),
              "success")
        return redirect(url_for("frontend.login"))

    return render_template("frontend/change_password.html", form=form)


@frontend.route('/reset_password', methods=['GET', 'POST'])
def reset_password():
    form = RecoverPasswordForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user:
            flash('Please see your email for instructions on '
                  'how to access your account', 'success')

            user.activation_key = str(uuid4())
            db.session.add(user)
            db.session.commit()

            url = url_for('frontend.change_password',
                          email=user.email,
                          activation_key=user.activation_key, _external=True)
            html = render_template('macros/_reset_password.html',
                                   project=current_app.config['PROJECT'],
                                   username=user.name, url=url)
            message = Message(subject='Reset your password in ' +
                              current_app.config['PROJECT'],
                              html=html,
                              recipients=[user.email])
            mail.send(message)

            return render_template('frontend/reset_password.html', form=form)
        else:
            flash(_('Sorry, no user found for that email address'), 'error')

    return render_template('frontend/reset_password.html', form=form)


@frontend.route('/help')
def help():
    return render_template('frontend/footers/help.html', active="help")

fbone/settings/__init__.py
# -*- coding: utf-8 -*-

from .views import settings     # NOQA

fbone/settings/views.py
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template, request, flash
from flask.ext.login import login_required, current_user

from ..extensions import db
from ..user import User
from .forms import PasswordForm


settings = Blueprint('settings', __name__, url_prefix='/settings')


@settings.route('/password', methods=['GET', 'POST'])
@login_required
def password():
    user = User.query.filter_by(name=current_user.name).first_or_404()
    form = PasswordForm(next=request.args.get('next'))

    if form.validate_on_submit():
        form.populate_obj(user)
        user.password = form.new_password.data

        db.session.add(user)
        db.session.commit()

        flash('Password updated.', 'success')

    return render_template('settings/password.html', user=user,
                           active="password", form=form)

fbone/user/__init__.py
# -*- coding: utf-8 -*-

from .models import User        # NOQA
from .views import user         # NOQA
from .constants import USER_ROLE, ADMIN, USER, USER_STATUS, NEW, ACTIVE  # NOQA

fbone/user/views.py
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template, abort
from flask.ext.login import login_required, current_user


user = Blueprint('user', __name__, url_prefix='/user')


@user.route('/')
@login_required
def index():
    if not current_user.is_authenticated():
        abort(403)
    return render_template('user/index.html', user=current_user)

fbone/templates/layouts/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>{% block title %}{{ page_title|default(_('WPIC')) }}{% endblock %} - WPIC</title>
    <meta name="description" content="Fbone (Flask bone) is a Flask (Python microframework) template/bootstrap/boilerplate application.">
    <meta name="author" content="Wilson Xu">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    <link rel="Shortcut Icon" href="{{ url_for('static', filename='favicon.png') }}" type="image/x-icon">

    {% block css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/vendor/normalize.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/vendor/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    {% endblock %}

    {% block css_style %}
    {% endblock %}

    {% block js_top %}
    <script src="{{ url_for('static', filename='js/vendor/modernizr-2.6.2.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/vendor/jquery-2.0.0.min.js') }}"></script>
    <!--
    {% set jquery_path = url_for('static', filename='js/vendor/jquery-1.8.3.min.js') %}
    <script>window.jQuery || document.write('<script src="{{ jquery_path }}"><\/script>')</script>
    -->
    {% endblock %}
</head>
<body>
    {% include "macros/_ask_user_to_update_ie.html" %}

    <div id='wrap'>
        {% block topbar %}
        <div class="navbar">
            <div class="navbar-inner">
                <div class="container">
                    <a class='brand' href='{{ url_for('frontend.index')}}'>WPIC Web Calendar</a>

                    {% if current_user.is_authenticated() %}
                    <form class="navbar-search pull-left" action="{{ url_for('frontend.search') }}">
                        <input type='text' class="search-query" name='keywords' value='{{ keywords|default('') }}' placeholder='Search' />
                    </form>
                    <div class="nav-collapse collapse pull-right">
                        <ul class="nav">
                            {% if current_user.is_admin() %}
                            <li><a href="{{ url_for('admin.index') }}">{{ current_user.name }}</a></li>
                            {% else %}
                            <li><a href="{{ url_for('user.index') }}">{{ current_user.name }}</a></li>
                            {% endif %}
                            <li><a href="{{ url_for('settings.password') }}">Settings</a></li>
                            <li><a href="{{ url_for('frontend.logout') }}">Log out</a></li>
                        </ul>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endblock %}

        {% block flash_message %}
            {% with messages = get_flashed_messages(with_categories=True) %}
                {% if messages %}
                <div class="container">
                    <div id='flash_message_container'>
                        {% for category, msg in messages %}
                            <div class="alert alert-{{ category }}">
                                <button type="button" class="close" data-dismiss="alert">×</button>
                                {{ msg }}
                            </div>
                        {% endfor %}
                    </div>
                </div>
                {% endif %}
            {% endwith %}
        {% endblock %}

        {% block container %}
        <div class="container">

            {% block top %}
                {% if tabs %}
                <div>
                    <ul class="nav nav-tabs">
                        {% for tab, link in tabs %}
                        <li class="{% if active == tab %}active{% endif %}">
                            <a href="{{ link }}">{{ tab|capitalize }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                {% endif %}
            {% endblock %}

            {% block body %}
            {% endblock %}

        </div>
        {% endblock %}
        <div id="push"></div>
    </div>

    <footer id="footer">
    </footer>

    {% block js_btm %}
    <script src="{{ url_for('static', filename='js/vendor/underscore-min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/vendor/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/vendor/calendar.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/plugins.js') }}"></script>
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
    {% endblock %}

    {% block js_user %}
    {% endblock %}

    {% block ga %}
    {% include "macros/_google_analytics.html" %}
    {% endblock %}
</body>
</html>